CLASS_NAMES = [
    "airplane",
    "breathing",
    "brushing_teeth",
    "can_opening",
    "car_horn",
    "cat",
    "chainsaw",
    "chirping_birds",
    "church_bells",
    "clapping",
    "clock_alarm",
    "clock_tick",
    "coughing",
    "cow",
    "crackling_fire",
    "crickets",
    "crow",
    "crying_baby",
    "dog",
    "door_wood_creaks",
    "door_wood_knock",
    "drinking_sipping",
    "engine",
    "fireworks",
    "footsteps",
    "frog",
    "glass_breaking",
    "hand_saw",
    "helicopter",
    "hen",
    "insects",
    "keyboard_typing",
    "laughing",
    "mouse_click",
    "pig",
    "pouring_water",
    "rain",
    "rooster",
    "sea_waves",
    "sheep",
    "siren",
    "sneezing",
    "snoring",
    "thunderstorm",
    "toilet_flush",
    "train",
    "vacuum_cleaner",
    "washing_machine",
    "water_drops",
    "wind",
]

DEMO_SAMPLES = [
    {
        "title": "Dog Bark Demo",
        "category": "dog",
        "caption": "Animal activity captured near a building entrance.",
        "filename": "1-100032-A-0.wav",
    },
    {
        "title": "Rain Demo",
        "category": "rain",
        "caption": "Weather-related ambient sound from the environment.",
        "filename": "1-17367-A-10.wav",
    },
    {
        "title": "Helicopter Demo",
        "category": "helicopter",
        "caption": "Mechanical aerial sound useful for surveillance scenarios.",
        "filename": "1-172649-A-40.wav",
    },
    {
        "title": "Siren Demo",
        "category": "siren",
        "caption": "Emergency alert sound for security and public safety.",
        "filename": "1-31482-A-42.wav",
    },
    {
        "title": "Footsteps Demo",
        "category": "footsteps",
        "caption": "Human activity sound for indoor surveillance scenarios.",
        "filename": "1-155858-A-25.wav",
    },
    {
        "title": "Hand Saw Demo",
        "category": "hand_saw",
        "caption": "Sharp cutting sound often linked with construction activity.",
        "filename": "1-18810-A-49.wav",
    },
    {
        "title": "Clock Alarm Demo",
        "category": "clock_alarm",
        "caption": "Alert-style sound useful for indoor monitoring examples.",
        "filename": "1-13613-A-37.wav",
    },
    {
        "title": "Glass Breaking Demo",
        "category": "glass_breaking",
        "caption": "Breakage sound relevant to intrusion and safety monitoring.",
        "filename": "1-20133-A-39.wav",
    },
    {
        "title": "Train Demo",
        "category": "train",
        "caption": "Transport-related environmental audio for city surveillance.",
        "filename": "1-119125-A-45.wav",
    },
    {
        "title": "Fire Demo",
        "category": "crackling_fire",
        "caption": "Fire-related ambience for hazard detection scenarios.",
        "filename": "1-17150-A-12.wav",
    },
    {
        "title": "Crying Baby Demo",
        "category": "crying_baby",
        "caption": "Human distress sound for smart monitoring applications.",
        "filename": "1-187207-A-20.wav",
    },
    {
        "title": "Cat Demo",
        "category": "cat",
        "caption": "Animal vocalization useful in residential environment demos.",
        "filename": "1-34094-A-5.wav",
    },
    {
        "title": "Car Horn Demo",
        "category": "car_horn",
        "caption": "Urban alert sound commonly found in traffic monitoring.",
        "filename": "1-17124-A-43.wav",
    },
    {
        "title": "Thunderstorm Demo",
        "category": "thunderstorm",
        "caption": "Severe weather ambience for environmental awareness demos.",
        "filename": "1-101296-A-19.wav",
    },
    {
        "title": "Church Bells Demo",
        "category": "church_bells",
        "caption": "Distinct outdoor ringing pattern for landmark-area audio scenes.",
        "filename": "1-13571-A-46.wav",
    },
]
